HW4 is completed
lixoi/lixoi-hw1 pull request #4
Opened 2023-02-25 20:14 UTC by lixoi

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [+] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [+] Я запустил `go mod tidy`.
- [+] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [+] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-02-25 20:15 UTC, lixoi commented
@ityulkanov добрый вечер. Смущает метод Clear )

2023-02-27 15:14 UTC, ityulkanov requested changes
Всё хорошо, только пара небольших комментов

2023-02-27 15:14 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	if v, ok := lc.items[key]; ok {
Вот тут, получается не соблюдено условие o(1),рекомендую воспользоваться дополнительным полем которое бы хранило ключ, таким образом мы можем уменьшить расход памяти

2023-02-27 20:01 UTC, lixoi commented on hw04_lru_cache/cache.go
> +	if v, ok := lc.items[key]; ok {
@ityulkanov поправил. Поигрался с неименованными структурами. Интересно, в Set я записывал valueItem, а в Get пытался получить значение через неименованную структуру 
return v.Value.(struct {
			val interface{}
			k   Key
		}).val, ok 
и компилятор ругался, что идет приведение разных типов. Странно, думал, он умнее )

2023-02-27 20:05 UTC, lixoi commented
@ityulkanov в задании идет акцент на метод Clear, я что-то не понял в чем там подвох )

2023-02-27 20:07 UTC, lixoi commented on hw04_lru_cache/list.go
> +	finitude *ListItem
@ityulkanov да, поправил

2023-02-28 09:03 UTC, ityulkanov approved these changes

2023-03-14 13:12 UTC, merged